name,value,relevant log,explanation
io.bytes.per.checksum,2019152374,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).
	",value-hit
dfs.client.read.striped.threadpool.size,18,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).
	",property-item-hit	read
yarn.resourcemanager.placement-constraints.algorithm.pool-size,1,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).
	",value-hit
dfs.client.max.block.acquire.failures,3,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).
	",value-hit
dfs.ha.zkfc.nn.http.timeout.ms,20000,"ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).
	",property-item-hit	ha
io.bytes.per.checksum,2019152374,ERROR	Task: attempt_1701359859177_0236_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).	,value-hit
yarn.resourcemanager.placement-constraints.algorithm.pool-size,1,ERROR	Task: attempt_1701359859177_0236_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).	,value-hit
dfs.client.max.block.acquire.failures,3,ERROR	Task: attempt_1701359859177_0236_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).	,value-hit
dfs.ha.zkfc.nn.http.timeout.ms,20000,ERROR	Task: attempt_1701359859177_0236_r_000001_0 - exited : org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).	,property-item-hit	ha
io.bytes.per.checksum,2019152374,INFO	Diagnostics report from attempt_1701359859177_0236_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).	,value-hit
yarn.resourcemanager.placement-constraints.algorithm.pool-size,1,INFO	Diagnostics report from attempt_1701359859177_0236_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).	,value-hit
dfs.client.max.block.acquire.failures,3,INFO	Diagnostics report from attempt_1701359859177_0236_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).	,value-hit
dfs.ha.zkfc.nn.http.timeout.ms,20000,INFO	Diagnostics report from attempt_1701359859177_0236_r_000001_0: Error: org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=2019152374) must divide block size (=134217728).	,property-item-hit	ha
yarn.resourcemanager.placement-constraints.algorithm.pool-size,1,INFO	1 failures on node 2f08f873c798,value-hit
dfs.client.max.block.acquire.failures,3,INFO	1 failures on node 2f08f873c798,value-hit
