yarn.client.failover-retries	0	ERROR	Thread Thread[eventHandlingThread,5,main] threw an Exception.org.apache.hadoop.HadoopIllegalArgumentException: Invalid values: dfs.bytes-per-checksum (=1490559308) must divide block size (=134217728).
		30